Traceback (most recent call last):
  File "/nlsasfs/home/ai4bharat/praveens/srija/assignment_1/train.py", line 398, in <module>
    main()
  File "/nlsasfs/home/ai4bharat/praveens/srija/assignment_1/train.py", line 117, in main
    loss_fn = build_loss_model(model, n_classes, hyperparameters)
  File "/nlsasfs/home/ai4bharat/praveens/srija/assignment_1/train.py", line 135, in build_loss_model
    return loss_fn(model, hyperparameters['regularizer'], hyperparameters['alpha'])
  File "/nlsasfs/home/ai4bharat/praveens/srija/assignment_1/modules/losses.py", line 45, in __init__
    super().__init()
AttributeError: 'super' object has no attribute '_NLLLoss__init'